### ISSUE TITLE
autotools-pkg-config-macro-not-cross-compilation-safe

### ISSUE THREAD

**Issue by kartikm** [apertium/apertium-hin#1]
Debian's Lintian tool reported this:

W: apertium-hin source: autotools-pkg-config-macro-not-cross-compilation-safe configure.ac (line 55)
N:
N:    The package appears to use AC_PATH_PROG to discover the location of
N:    pkg-config(1). This macro fails to select the correct version to support
N:    cross-compilation.
N:
N:    A better way would be to use the PKG_PROG_PKG_CONFIG macro from pkg.m4
N:    and then using the $PKG_CONFIG shell variable.
N:
N:    Refer to https://bugs.debian.org/884798 for details.
N:
N:    Severity: normal, Certainty: possible
N:
N:    Check: cruft, Type: source
N:

**Comment by kartikm** [comment]
@TinoDidriksen ^

**Comment by TinoDidriksen** [comment]
Yup, that's cruft that probably needs to be removed from many packages.

**Comment by priyankmodiPM** [comment]
Is this issue still open? I'd like to take it up (will need some help though)
